---
# OBS Configuration Role Default Variables
# ========================================

# OBS Configuration
obs_config:
  source_directory: "../../configs/obs/"
  target_base_directory: "C:/Tools/"
  copy_configs: true

# Installation Categories (for selective installation)
install_categories:
  essential: true
  development: true
  media: true
  gaming: true
  utilities: true
  scoop_packages: true
  windows_features: true

# Error Handling
error_handling:
  continue_on_package_failure: true
  package_failure_is_warning: true
  feature_failure_is_warning: false 