---
# Chocolatey Role Default Variables
# =================================

# Chocolatey Configuration
chocolatey:
  install_chocolatey: true
  packages:
    # Essential Packages (always installed)
    essential:
      - name: "firefox"
        description: "Privacy-focused web browser"
      - name: "7zip"
        description: "File archiver and compression tool"
    
    # Development Tools
    development:
      - name: "cursoride"
        description: "AI-powered code editor"
      - name: "git"
        description: "Version control system"
      - name: "docker-desktop"
        description: "Docker containerization platform"
    
    # Media Applications
    media:
      - name: "vlc"
        description: "Universal media player"
    
    # Gaming Platforms
    gaming:
      - name: "steam"
        description: "Digital game distribution platform"
      - name: "epicgameslauncher"
        description: "Epic Games digital distribution platform"
      - name: "goggalaxy"
        description: "GOG digital game distribution platform"
    
    # Utilities
    utilities:
      - name: "powertoys"
        description: "Windows system utilities"
      - name: "discord"
        description: "Voice and text chat for gamers"
      - name: "googledrive"
        description: "Google Drive sync client"
      - name: "flameshot"
        description: "Screenshot tool"
      - name: "teracopy"
        description: "File copy utility"
      - name: "mobaxterm"
        description: "Enhanced terminal for Windows"
      - name: "zoxide"
        description: "Smart cd command"
      # Note: These may need verification in Chocolatey
      - name: "nilesoft-shell"
        description: "Windows shell replacement"
        verify_exists: true
      - name: "streamdeck"
        description: "Elgato Stream Deck"
        verify_exists: true
      - name: "elgato-camerahub"
        description: "Elgato Camera Hub"
        verify_exists: true
      - name: "wavelink"
        description: "Elgato Wavelink"
        verify_exists: true

# Installation Categories (for selective installation)
install_categories:
  essential: true
  development: true
  media: true
  gaming: true
  utilities: true
  scoop_packages: true

# Error Handling
error_handling:
  continue_on_package_failure: true
  package_failure_is_warning: true
  feature_failure_is_warning: false 