---
# Ansible Inventory for Windows Computer Setup
# This inventory defines Windows target machines for configuration

all:
  children:
    windows:
      hosts:
        # Define your Windows target machines here
        # Example configurations:
        
        # For a specific Windows machine:
        # windows-desktop:
        #   ansible_host: 192.168.1.100
        #   ansible_user: Administrator
        #   ansible_password: "{{ vault_admin_password }}"
        #   ansible_connection: winrm
        #   ansible_winrm_server_cert_validation: ignore
        #   ansible_winrm_transport: ntlm
        #   ansible_winrm_port: 5985
        
        # For domain-joined machine:
        # windows-workstation:
        #   ansible_host: workstation.domain.local
        #   ansible_user: DOMAIN\\username
        #   ansible_password: "{{ vault_domain_password }}"
        #   ansible_connection: winrm
        #   ansible_winrm_server_cert_validation: ignore
        #   ansible_winrm_transport: kerberos
        #   ansible_winrm_port: 5985
        
        # For HTTPS WinRM (recommended for production):
        # windows-secure:
        #   ansible_host: 192.168.1.101
        #   ansible_user: Administrator
        #   ansible_password: "{{ vault_admin_password }}"
        #   ansible_connection: winrm
        #   ansible_winrm_server_cert_validation: ignore  # Set to 'validate' for production
        #   ansible_winrm_transport: ssl
        #   ansible_winrm_port: 5986
        
        # PLACEHOLDER - Replace with your actual Windows machine details
        target-windows:
          ansible_host: REPLACE_WITH_YOUR_WINDOWS_IP
          ansible_user: REPLACE_WITH_USERNAME
          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_transport: ntlm
          ansible_winrm_port: 5985
          
      vars:
        # Common Windows variables
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: System 