---
# Ansible Inventory for Windows Computer Setup
# This inventory defines Windows target machines for configuration

all:
  children:
    windows:
      hosts:
        # SSH-based Windows connection (recommended)
        target-windows:
          ansible_host: 10.0.60.215
          ansible_user: temp
          ansible_password: Balojsa
          ansible_connection: ssh
          ansible_shell_type: powershell
          ansible_ssh_shell_type: powershell
          ansible_become: true
          ansible_become_method: runas
          ansible_become_user: temp  # Will elevate this user when needed

      vars:
        # Common Windows variables for SSH
        ansible_shell_type: powershell
        ansible_become_method: runas
        # Common Windows variables
        ansible_become_user: System 