---
# Global Variables for Computer Setup
# ===================================

# Chocolatey Configuration
chocolatey:
  install_chocolatey: true
  packages:
    # Essential Packages (always installed)
    essential:
      - name: "firefox"
        description: "Privacy-focused web browser"
      - name: "7zip"
        description: "File archiver and compression tool"
    
    # Development Tools
    development:
      - name: "cursor"
        description: "AI-powered code editor"
      - name: "git"
        description: "Version control system"
      - name: "microsoft-windows-terminal"
        description: "Modern terminal application"
      - name: "docker-desktop"
        description: "Docker containerization platform"
    
    # Media Applications
    media:
      - name: "vlc"
        description: "Universal media player"
      - name: "spotify"
        description: "Music streaming service"
    
    # Gaming Platforms
    gaming:
      - name: "steam"
        description: "Digital game distribution platform"
      - name: "epicgameslauncher"
        description: "Epic Games digital distribution platform"
      - name: "goggalaxy"
        description: "GOG digital game distribution platform"
      - name: "battle.net"
        description: "Blizzard digital game distribution platform"
    
    # Utilities
    utilities:
      - name: "powertoys"
        description: "Windows system utilities"
      - name: "discord"
        description: "Voice and text chat for gamers"
      - name: "googledrive"
        description: "Google Drive sync client"
      - name: "flameshot"
        description: "Screenshot tool"
      - name: "teracopy"
        description: "File copy utility"
      - name: "mobaxterm"
        description: "Enhanced terminal for Windows"
      - name: "zoxide"
        description: "Smart cd command"
      # Note: These may need verification in Chocolatey
      - name: "nilesoft-shell"
        description: "Windows shell replacement"
        verify_exists: true
      - name: "elgato-wavelink"
        description: "Elgato Wavelink"
        verify_exists: true
      - name: "elgato-streamdeck"
        description: "Elgato Stream Deck"
        verify_exists: true
      - name: "elgato-camera-hub"
        description: "Elgato Camera Hub"
        verify_exists: true

# Scoop Configuration (for packages only available in Scoop)
scoop:
  install_scoop: true
  packages:
    - name: "fzf"
      description: "Fuzzy file finder"
    - name: "psfzf"
      description: "PowerShell wrapper for fzf"
    - name: "spotify-player"
      description: "Spotify terminal player"

# Installation Categories (for selective installation)
install_categories:
  essential: true
  development: true
  media: true
  gaming: true
  utilities: true
  scoop_packages: true

# Windows Features Configuration
windows_features:
  hyperv:
    enabled: true
    features:
      - "Microsoft-Hyper-V-All"
      - "Microsoft-Hyper-V"
      - "Microsoft-Hyper-V-Tools-All"
      - "Microsoft-Hyper-V-Management-PowerShell"
      - "Microsoft-Hyper-V-Hypervisor"
      - "Microsoft-Hyper-V-Services"
      - "Microsoft-Hyper-V-Management-Clients"
  
  windows_sandbox:
    enabled: true
    features:
      - "Containers-DisposableClientVM"
  
  wsl2:
    enabled: true
    features:
      - "Microsoft-Windows-Subsystem-Linux"
      - "VirtualMachinePlatform"

# PowerShell Configuration
powershell_config:
  profile_source: "../../configs/powershell/"
  profile_destination: "Documents/PowerShell/"
  copy_all_files: true

# OBS Configuration
obs_config:
  source_directory: "../../configs/obs/"
  target_base_directory: "C:/Tools/"
  copy_configs: true

# Firefox Configuration
firefox_config:
  source_directory: "../../configs/firefox/"
  copy_configs: true

# Error Handling
error_handling:
  continue_on_package_failure: true
  package_failure_is_warning: true
  feature_failure_is_warning: false

# Reboot Management
reboot:
  auto_reboot: true  # Enable automatic reboots by default
  reboot_timeout: 900  # 15 minutes timeout for safety 