---
# OBS Plugin Management Playbook
# ==============================
# Dedicated playbook for OBS plugin operations

- name: "OBS Plugin Management"
  hosts: windows
  gather_facts: no
  become: no
  
  tasks:
    - name: "Check OBS Plugin Status"
      include_role:
        name: obs_config
        tasks_from: check_plugin_status
      vars:
        profile_name: "{{ profile_item }}"
      loop: 
        - "Streaming"
        - "Recording"
        - "Testing"
      loop_control:
        loop_var: profile_item
      tags:
        - check
        - status

    - name: "Repair Missing OBS Plugins"
      include_role:
        name: obs_config
        tasks_from: repair_plugins
      tags:
        - repair
        - install

    - name: "Install Specific Profile Plugins"
      include_role:
        name: obs_config
        tasks_from: install_plugins
      vars:
        profile_name: "{{ target_profile | default('Streaming') }}"
        profile_plugins: "{{ obs_plugins[target_profile | default('Streaming')] | default([]) }}"
      when: target_profile is defined
      tags:
        - install_profile
        - specific 