---
# OBS Plugin Installation Tasks
# =============================
# Installs plugins for a specific OBS profile

- name: "Display plugin installation for {{ profile_name }}"
  debug:
    msg: "Installing {{ profile_plugins | length }} plugins for {{ profile_name }} profile: {{ profile_plugins | map(attribute='name') | join(', ') }}"

- name: "Install individual plugins for {{ profile_name }}"
  include_tasks: install_single_plugin.yml
  vars:
    plugin_name: "{{ plugin.name }}"
    plugin_url: "{{ plugin.url }}"
    target_profile: "{{ profile_name }}"
  loop: "{{ profile_plugins }}"
  loop_control:
    loop_var: plugin
  when: profile_plugins | length > 0

- name: "Clean up any leftover plugin downloads for {{ profile_name }}"
  win_find:
    paths: "{{ obs_config.target_base_directory }}\\{{ profile_name }}"
    patterns: "*.zip"
  register: leftover_zips

- name: "Remove leftover plugin zip files for {{ profile_name }}"
  win_file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ leftover_zips.files }}"
  failed_when: false

- name: "Verify plugin installation for {{ profile_name }}"
  win_find:
    paths: "{{ obs_config.target_base_directory }}\\{{ profile_name }}"
    patterns: "obs-plugins"
    file_type: directory
  register: plugin_verification

- name: "Display plugin verification for {{ profile_name }}"
  debug:
    msg: "Plugin installation completed for {{ profile_name }} - {{ 'obs-plugins directory found' if plugin_verification.files | length > 0 else 'no obs-plugins directory found' }}" 