---
# Chocolatey Role - Main Tasks
# ============================
# Installs Chocolatey package manager and all configured software packages

- name: "Check if Chocolatey is installed"
  win_stat:
    path: "C:\\ProgramData\\chocolatey\\choco.exe"
  register: chocolatey_installed
  tags: [chocolatey, software]

- name: "Install Chocolatey package manager"
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force;
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  when: not chocolatey_installed.stat.exists
  register: chocolatey_install_result
  tags: [chocolatey, software]

- name: "Force refresh environment variables after Chocolatey installation"
  win_shell: |
    # Multiple methods to ensure environment refresh
    refreshenv
    
    # Manually update PATH for current session
    $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("PATH", "User")
    
    # Specifically add Chocolatey to PATH if not present
    $chocoPath = "C:\ProgramData\chocolatey\bin"
    if ($env:PATH -notlike "*$chocoPath*") {
        $env:PATH = "$chocoPath;$env:PATH"
    }
    
    # Verify choco is now available
    $chocoExe = Get-Command choco.exe -ErrorAction SilentlyContinue
    if ($chocoExe) {
        Write-Output "Chocolatey found at: $($chocoExe.Source)"
    } else {
        Write-Output "Chocolatey still not found in PATH"
        throw "Failed to add Chocolatey to PATH"
    }
  when: chocolatey_install_result is changed
  register: chocolatey_refresh_result
  tags: [chocolatey, software]

- name: "Verify Chocolatey installation and PATH"
  win_shell: |
    # Try multiple ways to find and execute choco
    $chocoCommands = @(
        "choco",
        "C:\ProgramData\chocolatey\bin\choco.exe",
        "C:\ProgramData\chocolatey\choco.exe"
    )
    
    $chocoFound = $false
    foreach ($cmd in $chocoCommands) {
        try {
            $version = & $cmd --version 2>$null
            if ($version) {
                Write-Output "Chocolatey version: $version"
                Write-Output "Chocolatey command: $cmd"
                $chocoFound = $true
                break
            }
        } catch {
            continue
        }
    }
    
    if (-not $chocoFound) {
        throw "Chocolatey installation verification failed"
    }
  register: choco_version
  changed_when: false
  tags: [chocolatey, software]

- name: "Display Chocolatey version"
  debug:
    msg: "{{ choco_version.stdout_lines | join(' ') }}"
  tags: [chocolatey, software]

- name: "Install essential packages"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  register: essential_install_result
  failed_when: false
  loop: "{{ chocolatey.packages.essential }}"
  when: install_categories.essential | default(true)
  tags: [chocolatey, software, packages]

- name: "Report essential package failures"
  debug:
    msg: "Failed to install essential package: {{ item.item.name }} - {{ item.item.description }}"
  loop: "{{ essential_install_result.results }}"
  when: 
    - essential_install_result is defined
    - item.failed | default(false)
    - error_handling.package_failure_is_warning | default(true)
  tags: [chocolatey, software, packages]

- name: "Install development packages"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  register: development_install_result
  failed_when: false
  loop: "{{ chocolatey.packages.development }}"
  when: install_categories.development | default(true)
  tags: [chocolatey, software, packages]

- name: "Report development package failures"
  debug:
    msg: "Failed to install development package: {{ item.item.name }} - {{ item.item.description }}"
  loop: "{{ development_install_result.results }}"
  when: 
    - development_install_result is defined
    - item.failed | default(false)
    - error_handling.package_failure_is_warning | default(true)
  tags: [chocolatey, software, packages]

- name: "Install media packages"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  register: media_install_result
  failed_when: false
  loop: "{{ chocolatey.packages.media }}"
  when: install_categories.media | default(true)
  tags: [chocolatey, software, packages]

- name: "Report media package failures"
  debug:
    msg: "Failed to install media package: {{ item.item.name }} - {{ item.item.description }}"
  loop: "{{ media_install_result.results }}"
  when: 
    - media_install_result is defined
    - item.failed | default(false)
    - error_handling.package_failure_is_warning | default(true)
  tags: [chocolatey, software, packages]

- name: "Install gaming packages"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  register: gaming_install_result
  failed_when: false
  loop: "{{ chocolatey.packages.gaming }}"
  when: install_categories.gaming | default(true)
  tags: [chocolatey, software, packages]

- name: "Report gaming package failures"
  debug:
    msg: "Failed to install gaming package: {{ item.item.name }} - {{ item.item.description }}"
  loop: "{{ gaming_install_result.results }}"
  when: 
    - gaming_install_result is defined
    - item.failed | default(false)
    - error_handling.package_failure_is_warning | default(true)
  tags: [chocolatey, software, packages]

- name: "Install utility packages"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  register: utilities_install_result
  failed_when: false
  loop: "{{ chocolatey.packages.utilities }}"
  when: install_categories.utilities | default(true)
  tags: [chocolatey, software, packages]

- name: "Report utility package failures"
  debug:
    msg: "Failed to install utility package: {{ item.item.name }} - {{ item.item.description }}"
  loop: "{{ utilities_install_result.results }}"
  when: 
    - utilities_install_result is defined
    - item.failed | default(false)
    - error_handling.package_failure_is_warning | default(true)
  tags: [chocolatey, software, packages]

- name: "Create installation summary"
  set_fact:
    package_summary:
      essential: "{{ essential_install_result.results | default([]) | selectattr('failed', 'undefined') | list | length }}/{{ chocolatey.packages.essential | length }}"
      development: "{{ development_install_result.results | default([]) | selectattr('failed', 'undefined') | list | length }}/{{ chocolatey.packages.development | length }}"
      media: "{{ media_install_result.results | default([]) | selectattr('failed', 'undefined') | list | length }}/{{ chocolatey.packages.media | length }}"
      gaming: "{{ gaming_install_result.results | default([]) | selectattr('failed', 'undefined') | list | length }}/{{ chocolatey.packages.gaming | length }}"
      utilities: "{{ utilities_install_result.results | default([]) | selectattr('failed', 'undefined') | list | length }}/{{ chocolatey.packages.utilities | length }}"
  tags: [chocolatey, software]

- name: "Display installation summary"
  debug:
    msg: "Package installation completed - Essential: {{ package_summary.essential }}, Development: {{ package_summary.development }}, Media: {{ package_summary.media }}, Gaming: {{ package_summary.gaming }}, Utilities: {{ package_summary.utilities }}"
  tags: [chocolatey, software] 